### ISSUE TITLE
Wrong scrobbling music

### ISSUE THREAD

**Issue by MarconiGRF** [Erick2280/discord2lastfm#13]
It looks to have some trouble with the track recognition on the bot as can be seen on the screenshot below:

![image](https://user-images.githubusercontent.com/18905896/121794590-f1372280-cbdf-11eb-888e-5fba870bbd1d.png)

The search string on groovy was `-p electric avenue` which lead to [this music video on youtube](https://www.youtube.com/watch?v=IuwxZSIS__4).

**Comment by Erick2280** [comment]
Hi! Since Groovy Bot is no longer in service, I will close this issue.
