### ISSUE TITLE
Hydra bot isn't tracking

### ISSUE THREAD

**Issue by ypawar26** [Erick2280/discord2lastfm#19]
Cordscrobbler bot isn't tracking hydra songs please see into it.

**Comment by Erick2280** [comment]
Hi! Recent changes in the Hydra Bot embed formatting have broken the Cordscrobbler integration. I'm working on a solution ☺

**Comment by Erick2280** [comment]
Cordscrobbler 2.3.0 has been shipped, fixing Hydra Bot support 🚀
