### ISSUE TITLE
New music bot support needed

### ISSUE THREAD

**Issue by minimar** [Erick2280/discord2lastfm#21]
All three of the currently supported music bots have been struck by Google (except Hydra, which instead removed support for youtube)

Because of this, support for new music bots that haven't been taken down will be needed, such as [Jockie Music](https://www.jockiemusic.com/).

**Comment by Erick2280** [comment]
Hi! I'm working on new integrations for Cordscrobbler, including Jockie Music ☺

**Comment by Erick2280** [comment]
Cordscrobbler 2.3.0 has been shipped, now supporting Jockie Music, Chip and Tempo bots 🚀
